# Generated by Django 5.2.7 on 2025-10-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceplan',
            name='owner',
        ),
    ]
