# Generated by Django 5.2.7 on 2025-10-30 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0002_remove_insuranceplan_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('num_kids', models.PositiveIntegerField(default=0)),
                ('num_married', models.PositiveIntegerField(default=0)),
                ('tertiary_education', models.BooleanField(default=False)),
                ('cooker', models.BooleanField(default=False)),
                ('neat', models.BooleanField(default=False)),
                ('steady_income', models.BooleanField(default=False)),
                ('personality', models.PositiveIntegerField()),
                ('spirituality', models.PositiveBigIntegerField()),
                ('innocence', models.PositiveIntegerField()),
                ('premium_plan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insuranceplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
