# Generated by Django 5.2.7 on 2025-11-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='premium_plan',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='spirituality',
            field=models.PositiveIntegerField(),
        ),
    ]
